# Generated by Django 4.0.3 on 2022-03-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('brand', models.CharField(default=None, max_length=100)),
                ('product_details', models.CharField(default=None, max_length=500)),
                ('price', models.IntegerField(default=None)),
                ('image', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
