# Generated by Django 4.0.3 on 2022-03-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=500)),
                ('related_articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='articles.article')),
                ('related_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='products.product')),
            ],
        ),
    ]
