# Generated by Django 4.0.3 on 2022-03-06 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='related_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='products.product'),
        ),
    ]
