# Generated by Django 4.0.3 on 2022-03-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='related_products',
            field=models.ManyToManyField(related_name='brands', to='products.product'),
        ),
    ]
