# Generated by Django 4.0.3 on 2022-03-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='comment_likes',
        ),
    ]
