# Generated by Django 4.0.3 on 2022-03-09 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_rename_likes_comment_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_likes',
            field=models.ManyToManyField(default=None, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
